/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.banana.tables;


import com.johnsong.android.spring.jooq.banana.Banana;
import com.johnsong.android.spring.jooq.banana.tables.records.StoresummaryRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Storesummary extends TableImpl<StoresummaryRecord> {

    private static final long serialVersionUID = -231079965;

    /**
     * The reference instance of <code>banana.StoreSummary</code>
     */
    public static final Storesummary STORESUMMARY = new Storesummary();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoresummaryRecord> getRecordType() {
        return StoresummaryRecord.class;
    }

    /**
     * The column <code>banana.StoreSummary.store_id</code>.
     */
    public final TableField<StoresummaryRecord, Integer> STORE_ID = createField("store_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>banana.StoreSummary.name</code>.
     */
    public final TableField<StoresummaryRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>banana.StoreSummary.img</code>.
     */
    public final TableField<StoresummaryRecord, String> IMG = createField("img", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>banana.StoreSummary.lat</code>.
     */
    public final TableField<StoresummaryRecord, Double> LAT = createField("lat", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>banana.StoreSummary.lon</code>.
     */
    public final TableField<StoresummaryRecord, Double> LON = createField("lon", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>banana.StoreSummary.hit</code>.
     */
    public final TableField<StoresummaryRecord, Integer> HIT = createField("hit", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>banana.StoreSummary.review_count</code>.
     */
    public final TableField<StoresummaryRecord, Integer> REVIEW_COUNT = createField("review_count", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>banana.StoreSummary.score</code>.
     */
    public final TableField<StoresummaryRecord, Double> SCORE = createField("score", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>banana.StoreSummary.region_id</code>.
     */
    public final TableField<StoresummaryRecord, Integer> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>banana.StoreSummary.food_category_id</code>.
     */
    public final TableField<StoresummaryRecord, Integer> FOOD_CATEGORY_ID = createField("food_category_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>banana.StoreSummary</code> table reference
     */
    public Storesummary() {
        this(DSL.name("StoreSummary"), null);
    }

    /**
     * Create an aliased <code>banana.StoreSummary</code> table reference
     */
    public Storesummary(String alias) {
        this(DSL.name(alias), STORESUMMARY);
    }

    /**
     * Create an aliased <code>banana.StoreSummary</code> table reference
     */
    public Storesummary(Name alias) {
        this(alias, STORESUMMARY);
    }

    private Storesummary(Name alias, Table<StoresummaryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Storesummary(Name alias, Table<StoresummaryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Banana.BANANA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Storesummary as(String alias) {
        return new Storesummary(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Storesummary as(Name alias) {
        return new Storesummary(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Storesummary rename(String name) {
        return new Storesummary(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Storesummary rename(Name name) {
        return new Storesummary(name, null);
    }
}
