/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollationCharacterSetApplicability implements Serializable {

    private static final long serialVersionUID = 978246175;

    private final String collationName;
    private final String characterSetName;

    public CollationCharacterSetApplicability(CollationCharacterSetApplicability value) {
        this.collationName = value.collationName;
        this.characterSetName = value.characterSetName;
    }

    public CollationCharacterSetApplicability(
        String collationName,
        String characterSetName
    ) {
        this.collationName = collationName;
        this.characterSetName = characterSetName;
    }

    public String getCollationName() {
        return this.collationName;
    }

    public String getCharacterSetName() {
        return this.characterSetName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CollationCharacterSetApplicability (");

        sb.append(collationName);
        sb.append(", ").append(characterSetName);

        sb.append(")");
        return sb.toString();
    }
}
