/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collations implements Serializable {

    private static final long serialVersionUID = -525509412;

    private final String collationName;
    private final String characterSetName;
    private final Long   id;
    private final String isDefault;
    private final String isCompiled;
    private final Long   sortlen;

    public Collations(Collations value) {
        this.collationName = value.collationName;
        this.characterSetName = value.characterSetName;
        this.id = value.id;
        this.isDefault = value.isDefault;
        this.isCompiled = value.isCompiled;
        this.sortlen = value.sortlen;
    }

    public Collations(
        String collationName,
        String characterSetName,
        Long   id,
        String isDefault,
        String isCompiled,
        Long   sortlen
    ) {
        this.collationName = collationName;
        this.characterSetName = characterSetName;
        this.id = id;
        this.isDefault = isDefault;
        this.isCompiled = isCompiled;
        this.sortlen = sortlen;
    }

    public String getCollationName() {
        return this.collationName;
    }

    public String getCharacterSetName() {
        return this.characterSetName;
    }

    public Long getId() {
        return this.id;
    }

    public String getIsDefault() {
        return this.isDefault;
    }

    public String getIsCompiled() {
        return this.isCompiled;
    }

    public Long getSortlen() {
        return this.sortlen;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Collations (");

        sb.append(collationName);
        sb.append(", ").append(characterSetName);
        sb.append(", ").append(id);
        sb.append(", ").append(isDefault);
        sb.append(", ").append(isCompiled);
        sb.append(", ").append(sortlen);

        sb.append(")");
        return sb.toString();
    }
}
