/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Engines implements Serializable {

    private static final long serialVersionUID = -165090015;

    private final String engine;
    private final String support;
    private final String comment;
    private final String transactions;
    private final String xa;
    private final String savepoints;

    public Engines(Engines value) {
        this.engine = value.engine;
        this.support = value.support;
        this.comment = value.comment;
        this.transactions = value.transactions;
        this.xa = value.xa;
        this.savepoints = value.savepoints;
    }

    public Engines(
        String engine,
        String support,
        String comment,
        String transactions,
        String xa,
        String savepoints
    ) {
        this.engine = engine;
        this.support = support;
        this.comment = comment;
        this.transactions = transactions;
        this.xa = xa;
        this.savepoints = savepoints;
    }

    public String getEngine() {
        return this.engine;
    }

    public String getSupport() {
        return this.support;
    }

    public String getComment() {
        return this.comment;
    }

    public String getTransactions() {
        return this.transactions;
    }

    public String getXa() {
        return this.xa;
    }

    public String getSavepoints() {
        return this.savepoints;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Engines (");

        sb.append(engine);
        sb.append(", ").append(support);
        sb.append(", ").append(comment);
        sb.append(", ").append(transactions);
        sb.append(", ").append(xa);
        sb.append(", ").append(savepoints);

        sb.append(")");
        return sb.toString();
    }
}
