/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GlobalStatus implements Serializable {

    private static final long serialVersionUID = -1871273159;

    private final String variableName;
    private final String variableValue;

    public GlobalStatus(GlobalStatus value) {
        this.variableName = value.variableName;
        this.variableValue = value.variableValue;
    }

    public GlobalStatus(
        String variableName,
        String variableValue
    ) {
        this.variableName = variableName;
        this.variableValue = variableValue;
    }

    public String getVariableName() {
        return this.variableName;
    }

    public String getVariableValue() {
        return this.variableValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GlobalStatus (");

        sb.append(variableName);
        sb.append(", ").append(variableValue);

        sb.append(")");
        return sb.toString();
    }
}
