/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndexStatistics implements Serializable {

    private static final long serialVersionUID = 347494128;

    private final String tableSchema;
    private final String tableName;
    private final String indexName;
    private final Long   rowsRead;

    public IndexStatistics(IndexStatistics value) {
        this.tableSchema = value.tableSchema;
        this.tableName = value.tableName;
        this.indexName = value.indexName;
        this.rowsRead = value.rowsRead;
    }

    public IndexStatistics(
        String tableSchema,
        String tableName,
        String indexName,
        Long   rowsRead
    ) {
        this.tableSchema = tableSchema;
        this.tableName = tableName;
        this.indexName = indexName;
        this.rowsRead = rowsRead;
    }

    public String getTableSchema() {
        return this.tableSchema;
    }

    public String getTableName() {
        return this.tableName;
    }

    public String getIndexName() {
        return this.indexName;
    }

    public Long getRowsRead() {
        return this.rowsRead;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IndexStatistics (");

        sb.append(tableSchema);
        sb.append(", ").append(tableName);
        sb.append(", ").append(indexName);
        sb.append(", ").append(rowsRead);

        sb.append(")");
        return sb.toString();
    }
}
