/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbBufferPageLru implements Serializable {

    private static final long serialVersionUID = -1594637228;

    private final ULong  poolId;
    private final ULong  lruPosition;
    private final ULong  space;
    private final ULong  pageNumber;
    private final String pageType;
    private final ULong  flushType;
    private final ULong  fixCount;
    private final String isHashed;
    private final ULong  newestModification;
    private final ULong  oldestModification;
    private final ULong  accessTime;
    private final String tableName;
    private final String indexName;
    private final ULong  numberRecords;
    private final ULong  dataSize;
    private final ULong  compressedSize;
    private final String compressed;
    private final String ioFix;
    private final String isOld;
    private final ULong  freePageClock;

    public InnodbBufferPageLru(InnodbBufferPageLru value) {
        this.poolId = value.poolId;
        this.lruPosition = value.lruPosition;
        this.space = value.space;
        this.pageNumber = value.pageNumber;
        this.pageType = value.pageType;
        this.flushType = value.flushType;
        this.fixCount = value.fixCount;
        this.isHashed = value.isHashed;
        this.newestModification = value.newestModification;
        this.oldestModification = value.oldestModification;
        this.accessTime = value.accessTime;
        this.tableName = value.tableName;
        this.indexName = value.indexName;
        this.numberRecords = value.numberRecords;
        this.dataSize = value.dataSize;
        this.compressedSize = value.compressedSize;
        this.compressed = value.compressed;
        this.ioFix = value.ioFix;
        this.isOld = value.isOld;
        this.freePageClock = value.freePageClock;
    }

    public InnodbBufferPageLru(
        ULong  poolId,
        ULong  lruPosition,
        ULong  space,
        ULong  pageNumber,
        String pageType,
        ULong  flushType,
        ULong  fixCount,
        String isHashed,
        ULong  newestModification,
        ULong  oldestModification,
        ULong  accessTime,
        String tableName,
        String indexName,
        ULong  numberRecords,
        ULong  dataSize,
        ULong  compressedSize,
        String compressed,
        String ioFix,
        String isOld,
        ULong  freePageClock
    ) {
        this.poolId = poolId;
        this.lruPosition = lruPosition;
        this.space = space;
        this.pageNumber = pageNumber;
        this.pageType = pageType;
        this.flushType = flushType;
        this.fixCount = fixCount;
        this.isHashed = isHashed;
        this.newestModification = newestModification;
        this.oldestModification = oldestModification;
        this.accessTime = accessTime;
        this.tableName = tableName;
        this.indexName = indexName;
        this.numberRecords = numberRecords;
        this.dataSize = dataSize;
        this.compressedSize = compressedSize;
        this.compressed = compressed;
        this.ioFix = ioFix;
        this.isOld = isOld;
        this.freePageClock = freePageClock;
    }

    public ULong getPoolId() {
        return this.poolId;
    }

    public ULong getLruPosition() {
        return this.lruPosition;
    }

    public ULong getSpace() {
        return this.space;
    }

    public ULong getPageNumber() {
        return this.pageNumber;
    }

    public String getPageType() {
        return this.pageType;
    }

    public ULong getFlushType() {
        return this.flushType;
    }

    public ULong getFixCount() {
        return this.fixCount;
    }

    public String getIsHashed() {
        return this.isHashed;
    }

    public ULong getNewestModification() {
        return this.newestModification;
    }

    public ULong getOldestModification() {
        return this.oldestModification;
    }

    public ULong getAccessTime() {
        return this.accessTime;
    }

    public String getTableName() {
        return this.tableName;
    }

    public String getIndexName() {
        return this.indexName;
    }

    public ULong getNumberRecords() {
        return this.numberRecords;
    }

    public ULong getDataSize() {
        return this.dataSize;
    }

    public ULong getCompressedSize() {
        return this.compressedSize;
    }

    public String getCompressed() {
        return this.compressed;
    }

    public String getIoFix() {
        return this.ioFix;
    }

    public String getIsOld() {
        return this.isOld;
    }

    public ULong getFreePageClock() {
        return this.freePageClock;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbBufferPageLru (");

        sb.append(poolId);
        sb.append(", ").append(lruPosition);
        sb.append(", ").append(space);
        sb.append(", ").append(pageNumber);
        sb.append(", ").append(pageType);
        sb.append(", ").append(flushType);
        sb.append(", ").append(fixCount);
        sb.append(", ").append(isHashed);
        sb.append(", ").append(newestModification);
        sb.append(", ").append(oldestModification);
        sb.append(", ").append(accessTime);
        sb.append(", ").append(tableName);
        sb.append(", ").append(indexName);
        sb.append(", ").append(numberRecords);
        sb.append(", ").append(dataSize);
        sb.append(", ").append(compressedSize);
        sb.append(", ").append(compressed);
        sb.append(", ").append(ioFix);
        sb.append(", ").append(isOld);
        sb.append(", ").append(freePageClock);

        sb.append(")");
        return sb.toString();
    }
}
