/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbCmpmem implements Serializable {

    private static final long serialVersionUID = -648502508;

    private final Integer pageSize;
    private final Integer bufferPoolInstance;
    private final Integer pagesUsed;
    private final Integer pagesFree;
    private final Long    relocationOps;
    private final Integer relocationTime;

    public InnodbCmpmem(InnodbCmpmem value) {
        this.pageSize = value.pageSize;
        this.bufferPoolInstance = value.bufferPoolInstance;
        this.pagesUsed = value.pagesUsed;
        this.pagesFree = value.pagesFree;
        this.relocationOps = value.relocationOps;
        this.relocationTime = value.relocationTime;
    }

    public InnodbCmpmem(
        Integer pageSize,
        Integer bufferPoolInstance,
        Integer pagesUsed,
        Integer pagesFree,
        Long    relocationOps,
        Integer relocationTime
    ) {
        this.pageSize = pageSize;
        this.bufferPoolInstance = bufferPoolInstance;
        this.pagesUsed = pagesUsed;
        this.pagesFree = pagesFree;
        this.relocationOps = relocationOps;
        this.relocationTime = relocationTime;
    }

    public Integer getPageSize() {
        return this.pageSize;
    }

    public Integer getBufferPoolInstance() {
        return this.bufferPoolInstance;
    }

    public Integer getPagesUsed() {
        return this.pagesUsed;
    }

    public Integer getPagesFree() {
        return this.pagesFree;
    }

    public Long getRelocationOps() {
        return this.relocationOps;
    }

    public Integer getRelocationTime() {
        return this.relocationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbCmpmem (");

        sb.append(pageSize);
        sb.append(", ").append(bufferPoolInstance);
        sb.append(", ").append(pagesUsed);
        sb.append(", ").append(pagesFree);
        sb.append(", ").append(relocationOps);
        sb.append(", ").append(relocationTime);

        sb.append(")");
        return sb.toString();
    }
}
