/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbLockWaits implements Serializable {

    private static final long serialVersionUID = -1219671984;

    private final String requestingTrxId;
    private final String requestedLockId;
    private final String blockingTrxId;
    private final String blockingLockId;

    public InnodbLockWaits(InnodbLockWaits value) {
        this.requestingTrxId = value.requestingTrxId;
        this.requestedLockId = value.requestedLockId;
        this.blockingTrxId = value.blockingTrxId;
        this.blockingLockId = value.blockingLockId;
    }

    public InnodbLockWaits(
        String requestingTrxId,
        String requestedLockId,
        String blockingTrxId,
        String blockingLockId
    ) {
        this.requestingTrxId = requestingTrxId;
        this.requestedLockId = requestedLockId;
        this.blockingTrxId = blockingTrxId;
        this.blockingLockId = blockingLockId;
    }

    public String getRequestingTrxId() {
        return this.requestingTrxId;
    }

    public String getRequestedLockId() {
        return this.requestedLockId;
    }

    public String getBlockingTrxId() {
        return this.blockingTrxId;
    }

    public String getBlockingLockId() {
        return this.blockingLockId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbLockWaits (");

        sb.append(requestingTrxId);
        sb.append(", ").append(requestedLockId);
        sb.append(", ").append(blockingTrxId);
        sb.append(", ").append(blockingLockId);

        sb.append(")");
        return sb.toString();
    }
}
