/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysTablespaces implements Serializable {

    private static final long serialVersionUID = 1079082840;

    private final UInteger space;
    private final String   name;
    private final UInteger flag;
    private final String   fileFormat;
    private final String   rowFormat;
    private final UInteger pageSize;
    private final UInteger zipPageSize;

    public InnodbSysTablespaces(InnodbSysTablespaces value) {
        this.space = value.space;
        this.name = value.name;
        this.flag = value.flag;
        this.fileFormat = value.fileFormat;
        this.rowFormat = value.rowFormat;
        this.pageSize = value.pageSize;
        this.zipPageSize = value.zipPageSize;
    }

    public InnodbSysTablespaces(
        UInteger space,
        String   name,
        UInteger flag,
        String   fileFormat,
        String   rowFormat,
        UInteger pageSize,
        UInteger zipPageSize
    ) {
        this.space = space;
        this.name = name;
        this.flag = flag;
        this.fileFormat = fileFormat;
        this.rowFormat = rowFormat;
        this.pageSize = pageSize;
        this.zipPageSize = zipPageSize;
    }

    public UInteger getSpace() {
        return this.space;
    }

    public String getName() {
        return this.name;
    }

    public UInteger getFlag() {
        return this.flag;
    }

    public String getFileFormat() {
        return this.fileFormat;
    }

    public String getRowFormat() {
        return this.rowFormat;
    }

    public UInteger getPageSize() {
        return this.pageSize;
    }

    public UInteger getZipPageSize() {
        return this.zipPageSize;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbSysTablespaces (");

        sb.append(space);
        sb.append(", ").append(name);
        sb.append(", ").append(flag);
        sb.append(", ").append(fileFormat);
        sb.append(", ").append(rowFormat);
        sb.append(", ").append(pageSize);
        sb.append(", ").append(zipPageSize);

        sb.append(")");
        return sb.toString();
    }
}
