/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysColumns implements Serializable {

    private static final long serialVersionUID = -833878864;

    private final ULong   tableId;
    private final String  name;
    private final ULong   pos;
    private final Integer mtype;
    private final Integer prtype;
    private final Integer len;

    public InnodbSysColumns(InnodbSysColumns value) {
        this.tableId = value.tableId;
        this.name = value.name;
        this.pos = value.pos;
        this.mtype = value.mtype;
        this.prtype = value.prtype;
        this.len = value.len;
    }

    public InnodbSysColumns(
        ULong   tableId,
        String  name,
        ULong   pos,
        Integer mtype,
        Integer prtype,
        Integer len
    ) {
        this.tableId = tableId;
        this.name = name;
        this.pos = pos;
        this.mtype = mtype;
        this.prtype = prtype;
        this.len = len;
    }

    public ULong getTableId() {
        return this.tableId;
    }

    public String getName() {
        return this.name;
    }

    public ULong getPos() {
        return this.pos;
    }

    public Integer getMtype() {
        return this.mtype;
    }

    public Integer getPrtype() {
        return this.prtype;
    }

    public Integer getLen() {
        return this.len;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbSysColumns (");

        sb.append(tableId);
        sb.append(", ").append(name);
        sb.append(", ").append(pos);
        sb.append(", ").append(mtype);
        sb.append(", ").append(prtype);
        sb.append(", ").append(len);

        sb.append(")");
        return sb.toString();
    }
}
