/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysFields implements Serializable {

    private static final long serialVersionUID = -1325596855;

    private final ULong    indexId;
    private final String   name;
    private final UInteger pos;

    public InnodbSysFields(InnodbSysFields value) {
        this.indexId = value.indexId;
        this.name = value.name;
        this.pos = value.pos;
    }

    public InnodbSysFields(
        ULong    indexId,
        String   name,
        UInteger pos
    ) {
        this.indexId = indexId;
        this.name = name;
        this.pos = pos;
    }

    public ULong getIndexId() {
        return this.indexId;
    }

    public String getName() {
        return this.name;
    }

    public UInteger getPos() {
        return this.pos;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbSysFields (");

        sb.append(indexId);
        sb.append(", ").append(name);
        sb.append(", ").append(pos);

        sb.append(")");
        return sb.toString();
    }
}
