/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysIndexes implements Serializable {

    private static final long serialVersionUID = -1801228577;

    private final ULong   indexId;
    private final String  name;
    private final ULong   tableId;
    private final Integer type;
    private final Integer nFields;
    private final Integer pageNo;
    private final Integer space;

    public InnodbSysIndexes(InnodbSysIndexes value) {
        this.indexId = value.indexId;
        this.name = value.name;
        this.tableId = value.tableId;
        this.type = value.type;
        this.nFields = value.nFields;
        this.pageNo = value.pageNo;
        this.space = value.space;
    }

    public InnodbSysIndexes(
        ULong   indexId,
        String  name,
        ULong   tableId,
        Integer type,
        Integer nFields,
        Integer pageNo,
        Integer space
    ) {
        this.indexId = indexId;
        this.name = name;
        this.tableId = tableId;
        this.type = type;
        this.nFields = nFields;
        this.pageNo = pageNo;
        this.space = space;
    }

    public ULong getIndexId() {
        return this.indexId;
    }

    public String getName() {
        return this.name;
    }

    public ULong getTableId() {
        return this.tableId;
    }

    public Integer getType() {
        return this.type;
    }

    public Integer getNFields() {
        return this.nFields;
    }

    public Integer getPageNo() {
        return this.pageNo;
    }

    public Integer getSpace() {
        return this.space;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbSysIndexes (");

        sb.append(indexId);
        sb.append(", ").append(name);
        sb.append(", ").append(tableId);
        sb.append(", ").append(type);
        sb.append(", ").append(nFields);
        sb.append(", ").append(pageNo);
        sb.append(", ").append(space);

        sb.append(")");
        return sb.toString();
    }
}
