/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbMetrics implements Serializable {

    private static final long serialVersionUID = 159910147;

    private final String    name;
    private final String    subsystem;
    private final Long      count;
    private final Long      maxCount;
    private final Long      minCount;
    private final Double    avgCount;
    private final Long      countReset;
    private final Long      maxCountReset;
    private final Long      minCountReset;
    private final Double    avgCountReset;
    private final Timestamp timeEnabled;
    private final Timestamp timeDisabled;
    private final Long      timeElapsed;
    private final Timestamp timeReset;
    private final String    status;
    private final String    type;
    private final String    comment;

    public InnodbMetrics(InnodbMetrics value) {
        this.name = value.name;
        this.subsystem = value.subsystem;
        this.count = value.count;
        this.maxCount = value.maxCount;
        this.minCount = value.minCount;
        this.avgCount = value.avgCount;
        this.countReset = value.countReset;
        this.maxCountReset = value.maxCountReset;
        this.minCountReset = value.minCountReset;
        this.avgCountReset = value.avgCountReset;
        this.timeEnabled = value.timeEnabled;
        this.timeDisabled = value.timeDisabled;
        this.timeElapsed = value.timeElapsed;
        this.timeReset = value.timeReset;
        this.status = value.status;
        this.type = value.type;
        this.comment = value.comment;
    }

    public InnodbMetrics(
        String    name,
        String    subsystem,
        Long      count,
        Long      maxCount,
        Long      minCount,
        Double    avgCount,
        Long      countReset,
        Long      maxCountReset,
        Long      minCountReset,
        Double    avgCountReset,
        Timestamp timeEnabled,
        Timestamp timeDisabled,
        Long      timeElapsed,
        Timestamp timeReset,
        String    status,
        String    type,
        String    comment
    ) {
        this.name = name;
        this.subsystem = subsystem;
        this.count = count;
        this.maxCount = maxCount;
        this.minCount = minCount;
        this.avgCount = avgCount;
        this.countReset = countReset;
        this.maxCountReset = maxCountReset;
        this.minCountReset = minCountReset;
        this.avgCountReset = avgCountReset;
        this.timeEnabled = timeEnabled;
        this.timeDisabled = timeDisabled;
        this.timeElapsed = timeElapsed;
        this.timeReset = timeReset;
        this.status = status;
        this.type = type;
        this.comment = comment;
    }

    public String getName() {
        return this.name;
    }

    public String getSubsystem() {
        return this.subsystem;
    }

    public Long getCount() {
        return this.count;
    }

    public Long getMaxCount() {
        return this.maxCount;
    }

    public Long getMinCount() {
        return this.minCount;
    }

    public Double getAvgCount() {
        return this.avgCount;
    }

    public Long getCountReset() {
        return this.countReset;
    }

    public Long getMaxCountReset() {
        return this.maxCountReset;
    }

    public Long getMinCountReset() {
        return this.minCountReset;
    }

    public Double getAvgCountReset() {
        return this.avgCountReset;
    }

    public Timestamp getTimeEnabled() {
        return this.timeEnabled;
    }

    public Timestamp getTimeDisabled() {
        return this.timeDisabled;
    }

    public Long getTimeElapsed() {
        return this.timeElapsed;
    }

    public Timestamp getTimeReset() {
        return this.timeReset;
    }

    public String getStatus() {
        return this.status;
    }

    public String getType() {
        return this.type;
    }

    public String getComment() {
        return this.comment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbMetrics (");

        sb.append(name);
        sb.append(", ").append(subsystem);
        sb.append(", ").append(count);
        sb.append(", ").append(maxCount);
        sb.append(", ").append(minCount);
        sb.append(", ").append(avgCount);
        sb.append(", ").append(countReset);
        sb.append(", ").append(maxCountReset);
        sb.append(", ").append(minCountReset);
        sb.append(", ").append(avgCountReset);
        sb.append(", ").append(timeEnabled);
        sb.append(", ").append(timeDisabled);
        sb.append(", ").append(timeElapsed);
        sb.append(", ").append(timeReset);
        sb.append(", ").append(status);
        sb.append(", ").append(type);
        sb.append(", ").append(comment);

        sb.append(")");
        return sb.toString();
    }
}
