/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbChangedPages implements Serializable {

    private static final long serialVersionUID = -2100817106;

    private final UInteger spaceId;
    private final UInteger pageId;
    private final ULong    startLsn;
    private final ULong    endLsn;

    public InnodbChangedPages(InnodbChangedPages value) {
        this.spaceId = value.spaceId;
        this.pageId = value.pageId;
        this.startLsn = value.startLsn;
        this.endLsn = value.endLsn;
    }

    public InnodbChangedPages(
        UInteger spaceId,
        UInteger pageId,
        ULong    startLsn,
        ULong    endLsn
    ) {
        this.spaceId = spaceId;
        this.pageId = pageId;
        this.startLsn = startLsn;
        this.endLsn = endLsn;
    }

    public UInteger getSpaceId() {
        return this.spaceId;
    }

    public UInteger getPageId() {
        return this.pageId;
    }

    public ULong getStartLsn() {
        return this.startLsn;
    }

    public ULong getEndLsn() {
        return this.endLsn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbChangedPages (");

        sb.append(spaceId);
        sb.append(", ").append(pageId);
        sb.append(", ").append(startLsn);
        sb.append(", ").append(endLsn);

        sb.append(")");
        return sb.toString();
    }
}
