/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysDatafiles implements Serializable {

    private static final long serialVersionUID = 14768118;

    private final UInteger space;
    private final String   path;

    public InnodbSysDatafiles(InnodbSysDatafiles value) {
        this.space = value.space;
        this.path = value.path;
    }

    public InnodbSysDatafiles(
        UInteger space,
        String   path
    ) {
        this.space = space;
        this.path = path;
    }

    public UInteger getSpace() {
        return this.space;
    }

    public String getPath() {
        return this.path;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbSysDatafiles (");

        sb.append(space);
        sb.append(", ").append(path);

        sb.append(")");
        return sb.toString();
    }
}
