/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysTables implements Serializable {

    private static final long serialVersionUID = -861822151;

    private final ULong    tableId;
    private final String   name;
    private final Integer  flag;
    private final Integer  nCols;
    private final Integer  space;
    private final String   fileFormat;
    private final String   rowFormat;
    private final UInteger zipPageSize;

    public InnodbSysTables(InnodbSysTables value) {
        this.tableId = value.tableId;
        this.name = value.name;
        this.flag = value.flag;
        this.nCols = value.nCols;
        this.space = value.space;
        this.fileFormat = value.fileFormat;
        this.rowFormat = value.rowFormat;
        this.zipPageSize = value.zipPageSize;
    }

    public InnodbSysTables(
        ULong    tableId,
        String   name,
        Integer  flag,
        Integer  nCols,
        Integer  space,
        String   fileFormat,
        String   rowFormat,
        UInteger zipPageSize
    ) {
        this.tableId = tableId;
        this.name = name;
        this.flag = flag;
        this.nCols = nCols;
        this.space = space;
        this.fileFormat = fileFormat;
        this.rowFormat = rowFormat;
        this.zipPageSize = zipPageSize;
    }

    public ULong getTableId() {
        return this.tableId;
    }

    public String getName() {
        return this.name;
    }

    public Integer getFlag() {
        return this.flag;
    }

    public Integer getNCols() {
        return this.nCols;
    }

    public Integer getSpace() {
        return this.space;
    }

    public String getFileFormat() {
        return this.fileFormat;
    }

    public String getRowFormat() {
        return this.rowFormat;
    }

    public UInteger getZipPageSize() {
        return this.zipPageSize;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbSysTables (");

        sb.append(tableId);
        sb.append(", ").append(name);
        sb.append(", ").append(flag);
        sb.append(", ").append(nCols);
        sb.append(", ").append(space);
        sb.append(", ").append(fileFormat);
        sb.append(", ").append(rowFormat);
        sb.append(", ").append(zipPageSize);

        sb.append(")");
        return sb.toString();
    }
}
