/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysForeign implements Serializable {

    private static final long serialVersionUID = -681775709;

    private final String   id;
    private final String   forName;
    private final String   refName;
    private final UInteger nCols;
    private final UInteger type;

    public InnodbSysForeign(InnodbSysForeign value) {
        this.id = value.id;
        this.forName = value.forName;
        this.refName = value.refName;
        this.nCols = value.nCols;
        this.type = value.type;
    }

    public InnodbSysForeign(
        String   id,
        String   forName,
        String   refName,
        UInteger nCols,
        UInteger type
    ) {
        this.id = id;
        this.forName = forName;
        this.refName = refName;
        this.nCols = nCols;
        this.type = type;
    }

    public String getId() {
        return this.id;
    }

    public String getForName() {
        return this.forName;
    }

    public String getRefName() {
        return this.refName;
    }

    public UInteger getNCols() {
        return this.nCols;
    }

    public UInteger getType() {
        return this.type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbSysForeign (");

        sb.append(id);
        sb.append(", ").append(forName);
        sb.append(", ").append(refName);
        sb.append(", ").append(nCols);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
