/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysTablestats implements Serializable {

    private static final long serialVersionUID = -1139589416;

    private final ULong   tableId;
    private final String  name;
    private final String  statsInitialized;
    private final ULong   numRows;
    private final ULong   clustIndexSize;
    private final ULong   otherIndexSize;
    private final ULong   modifiedCounter;
    private final ULong   autoinc;
    private final Integer refCount;

    public InnodbSysTablestats(InnodbSysTablestats value) {
        this.tableId = value.tableId;
        this.name = value.name;
        this.statsInitialized = value.statsInitialized;
        this.numRows = value.numRows;
        this.clustIndexSize = value.clustIndexSize;
        this.otherIndexSize = value.otherIndexSize;
        this.modifiedCounter = value.modifiedCounter;
        this.autoinc = value.autoinc;
        this.refCount = value.refCount;
    }

    public InnodbSysTablestats(
        ULong   tableId,
        String  name,
        String  statsInitialized,
        ULong   numRows,
        ULong   clustIndexSize,
        ULong   otherIndexSize,
        ULong   modifiedCounter,
        ULong   autoinc,
        Integer refCount
    ) {
        this.tableId = tableId;
        this.name = name;
        this.statsInitialized = statsInitialized;
        this.numRows = numRows;
        this.clustIndexSize = clustIndexSize;
        this.otherIndexSize = otherIndexSize;
        this.modifiedCounter = modifiedCounter;
        this.autoinc = autoinc;
        this.refCount = refCount;
    }

    public ULong getTableId() {
        return this.tableId;
    }

    public String getName() {
        return this.name;
    }

    public String getStatsInitialized() {
        return this.statsInitialized;
    }

    public ULong getNumRows() {
        return this.numRows;
    }

    public ULong getClustIndexSize() {
        return this.clustIndexSize;
    }

    public ULong getOtherIndexSize() {
        return this.otherIndexSize;
    }

    public ULong getModifiedCounter() {
        return this.modifiedCounter;
    }

    public ULong getAutoinc() {
        return this.autoinc;
    }

    public Integer getRefCount() {
        return this.refCount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbSysTablestats (");

        sb.append(tableId);
        sb.append(", ").append(name);
        sb.append(", ").append(statsInitialized);
        sb.append(", ").append(numRows);
        sb.append(", ").append(clustIndexSize);
        sb.append(", ").append(otherIndexSize);
        sb.append(", ").append(modifiedCounter);
        sb.append(", ").append(autoinc);
        sb.append(", ").append(refCount);

        sb.append(")");
        return sb.toString();
    }
}
