/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plugins implements Serializable {

    private static final long serialVersionUID = 1242962492;

    private final String pluginName;
    private final String pluginVersion;
    private final String pluginStatus;
    private final String pluginType;
    private final String pluginTypeVersion;
    private final String pluginLibrary;
    private final String pluginLibraryVersion;
    private final String pluginAuthor;
    private final String pluginDescription;
    private final String pluginLicense;
    private final String loadOption;
    private final String pluginMaturity;
    private final String pluginAuthVersion;

    public Plugins(Plugins value) {
        this.pluginName = value.pluginName;
        this.pluginVersion = value.pluginVersion;
        this.pluginStatus = value.pluginStatus;
        this.pluginType = value.pluginType;
        this.pluginTypeVersion = value.pluginTypeVersion;
        this.pluginLibrary = value.pluginLibrary;
        this.pluginLibraryVersion = value.pluginLibraryVersion;
        this.pluginAuthor = value.pluginAuthor;
        this.pluginDescription = value.pluginDescription;
        this.pluginLicense = value.pluginLicense;
        this.loadOption = value.loadOption;
        this.pluginMaturity = value.pluginMaturity;
        this.pluginAuthVersion = value.pluginAuthVersion;
    }

    public Plugins(
        String pluginName,
        String pluginVersion,
        String pluginStatus,
        String pluginType,
        String pluginTypeVersion,
        String pluginLibrary,
        String pluginLibraryVersion,
        String pluginAuthor,
        String pluginDescription,
        String pluginLicense,
        String loadOption,
        String pluginMaturity,
        String pluginAuthVersion
    ) {
        this.pluginName = pluginName;
        this.pluginVersion = pluginVersion;
        this.pluginStatus = pluginStatus;
        this.pluginType = pluginType;
        this.pluginTypeVersion = pluginTypeVersion;
        this.pluginLibrary = pluginLibrary;
        this.pluginLibraryVersion = pluginLibraryVersion;
        this.pluginAuthor = pluginAuthor;
        this.pluginDescription = pluginDescription;
        this.pluginLicense = pluginLicense;
        this.loadOption = loadOption;
        this.pluginMaturity = pluginMaturity;
        this.pluginAuthVersion = pluginAuthVersion;
    }

    public String getPluginName() {
        return this.pluginName;
    }

    public String getPluginVersion() {
        return this.pluginVersion;
    }

    public String getPluginStatus() {
        return this.pluginStatus;
    }

    public String getPluginType() {
        return this.pluginType;
    }

    public String getPluginTypeVersion() {
        return this.pluginTypeVersion;
    }

    public String getPluginLibrary() {
        return this.pluginLibrary;
    }

    public String getPluginLibraryVersion() {
        return this.pluginLibraryVersion;
    }

    public String getPluginAuthor() {
        return this.pluginAuthor;
    }

    public String getPluginDescription() {
        return this.pluginDescription;
    }

    public String getPluginLicense() {
        return this.pluginLicense;
    }

    public String getLoadOption() {
        return this.loadOption;
    }

    public String getPluginMaturity() {
        return this.pluginMaturity;
    }

    public String getPluginAuthVersion() {
        return this.pluginAuthVersion;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Plugins (");

        sb.append(pluginName);
        sb.append(", ").append(pluginVersion);
        sb.append(", ").append(pluginStatus);
        sb.append(", ").append(pluginType);
        sb.append(", ").append(pluginTypeVersion);
        sb.append(", ").append(pluginLibrary);
        sb.append(", ").append(pluginLibraryVersion);
        sb.append(", ").append(pluginAuthor);
        sb.append(", ").append(pluginDescription);
        sb.append(", ").append(pluginLicense);
        sb.append(", ").append(loadOption);
        sb.append(", ").append(pluginMaturity);
        sb.append(", ").append(pluginAuthVersion);

        sb.append(")");
        return sb.toString();
    }
}
