/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Processlist implements Serializable {

    private static final long serialVersionUID = -1814676508;

    private final Long       id;
    private final String     user;
    private final String     host;
    private final String     db;
    private final String     command;
    private final Integer    time;
    private final String     state;
    private final String     info;
    private final BigDecimal timeMs;
    private final Byte       stage;
    private final Byte       maxStage;
    private final BigDecimal progress;
    private final Integer    memoryUsed;
    private final Integer    examinedRows;
    private final Long       queryId;

    public Processlist(Processlist value) {
        this.id = value.id;
        this.user = value.user;
        this.host = value.host;
        this.db = value.db;
        this.command = value.command;
        this.time = value.time;
        this.state = value.state;
        this.info = value.info;
        this.timeMs = value.timeMs;
        this.stage = value.stage;
        this.maxStage = value.maxStage;
        this.progress = value.progress;
        this.memoryUsed = value.memoryUsed;
        this.examinedRows = value.examinedRows;
        this.queryId = value.queryId;
    }

    public Processlist(
        Long       id,
        String     user,
        String     host,
        String     db,
        String     command,
        Integer    time,
        String     state,
        String     info,
        BigDecimal timeMs,
        Byte       stage,
        Byte       maxStage,
        BigDecimal progress,
        Integer    memoryUsed,
        Integer    examinedRows,
        Long       queryId
    ) {
        this.id = id;
        this.user = user;
        this.host = host;
        this.db = db;
        this.command = command;
        this.time = time;
        this.state = state;
        this.info = info;
        this.timeMs = timeMs;
        this.stage = stage;
        this.maxStage = maxStage;
        this.progress = progress;
        this.memoryUsed = memoryUsed;
        this.examinedRows = examinedRows;
        this.queryId = queryId;
    }

    public Long getId() {
        return this.id;
    }

    public String getUser() {
        return this.user;
    }

    public String getHost() {
        return this.host;
    }

    public String getDb() {
        return this.db;
    }

    public String getCommand() {
        return this.command;
    }

    public Integer getTime() {
        return this.time;
    }

    public String getState() {
        return this.state;
    }

    public String getInfo() {
        return this.info;
    }

    public BigDecimal getTimeMs() {
        return this.timeMs;
    }

    public Byte getStage() {
        return this.stage;
    }

    public Byte getMaxStage() {
        return this.maxStage;
    }

    public BigDecimal getProgress() {
        return this.progress;
    }

    public Integer getMemoryUsed() {
        return this.memoryUsed;
    }

    public Integer getExaminedRows() {
        return this.examinedRows;
    }

    public Long getQueryId() {
        return this.queryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Processlist (");

        sb.append(id);
        sb.append(", ").append(user);
        sb.append(", ").append(host);
        sb.append(", ").append(db);
        sb.append(", ").append(command);
        sb.append(", ").append(time);
        sb.append(", ").append(state);
        sb.append(", ").append(info);
        sb.append(", ").append(timeMs);
        sb.append(", ").append(stage);
        sb.append(", ").append(maxStage);
        sb.append(", ").append(progress);
        sb.append(", ").append(memoryUsed);
        sb.append(", ").append(examinedRows);
        sb.append(", ").append(queryId);

        sb.append(")");
        return sb.toString();
    }
}
