/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profiling implements Serializable {

    private static final long serialVersionUID = -115405898;

    private final Integer    queryId;
    private final Integer    seq;
    private final String     state;
    private final BigDecimal duration;
    private final BigDecimal cpuUser;
    private final BigDecimal cpuSystem;
    private final Integer    contextVoluntary;
    private final Integer    contextInvoluntary;
    private final Integer    blockOpsIn;
    private final Integer    blockOpsOut;
    private final Integer    messagesSent;
    private final Integer    messagesReceived;
    private final Integer    pageFaultsMajor;
    private final Integer    pageFaultsMinor;
    private final Integer    swaps;
    private final String     sourceFunction;
    private final String     sourceFile;
    private final Integer    sourceLine;

    public Profiling(Profiling value) {
        this.queryId = value.queryId;
        this.seq = value.seq;
        this.state = value.state;
        this.duration = value.duration;
        this.cpuUser = value.cpuUser;
        this.cpuSystem = value.cpuSystem;
        this.contextVoluntary = value.contextVoluntary;
        this.contextInvoluntary = value.contextInvoluntary;
        this.blockOpsIn = value.blockOpsIn;
        this.blockOpsOut = value.blockOpsOut;
        this.messagesSent = value.messagesSent;
        this.messagesReceived = value.messagesReceived;
        this.pageFaultsMajor = value.pageFaultsMajor;
        this.pageFaultsMinor = value.pageFaultsMinor;
        this.swaps = value.swaps;
        this.sourceFunction = value.sourceFunction;
        this.sourceFile = value.sourceFile;
        this.sourceLine = value.sourceLine;
    }

    public Profiling(
        Integer    queryId,
        Integer    seq,
        String     state,
        BigDecimal duration,
        BigDecimal cpuUser,
        BigDecimal cpuSystem,
        Integer    contextVoluntary,
        Integer    contextInvoluntary,
        Integer    blockOpsIn,
        Integer    blockOpsOut,
        Integer    messagesSent,
        Integer    messagesReceived,
        Integer    pageFaultsMajor,
        Integer    pageFaultsMinor,
        Integer    swaps,
        String     sourceFunction,
        String     sourceFile,
        Integer    sourceLine
    ) {
        this.queryId = queryId;
        this.seq = seq;
        this.state = state;
        this.duration = duration;
        this.cpuUser = cpuUser;
        this.cpuSystem = cpuSystem;
        this.contextVoluntary = contextVoluntary;
        this.contextInvoluntary = contextInvoluntary;
        this.blockOpsIn = blockOpsIn;
        this.blockOpsOut = blockOpsOut;
        this.messagesSent = messagesSent;
        this.messagesReceived = messagesReceived;
        this.pageFaultsMajor = pageFaultsMajor;
        this.pageFaultsMinor = pageFaultsMinor;
        this.swaps = swaps;
        this.sourceFunction = sourceFunction;
        this.sourceFile = sourceFile;
        this.sourceLine = sourceLine;
    }

    public Integer getQueryId() {
        return this.queryId;
    }

    public Integer getSeq() {
        return this.seq;
    }

    public String getState() {
        return this.state;
    }

    public BigDecimal getDuration() {
        return this.duration;
    }

    public BigDecimal getCpuUser() {
        return this.cpuUser;
    }

    public BigDecimal getCpuSystem() {
        return this.cpuSystem;
    }

    public Integer getContextVoluntary() {
        return this.contextVoluntary;
    }

    public Integer getContextInvoluntary() {
        return this.contextInvoluntary;
    }

    public Integer getBlockOpsIn() {
        return this.blockOpsIn;
    }

    public Integer getBlockOpsOut() {
        return this.blockOpsOut;
    }

    public Integer getMessagesSent() {
        return this.messagesSent;
    }

    public Integer getMessagesReceived() {
        return this.messagesReceived;
    }

    public Integer getPageFaultsMajor() {
        return this.pageFaultsMajor;
    }

    public Integer getPageFaultsMinor() {
        return this.pageFaultsMinor;
    }

    public Integer getSwaps() {
        return this.swaps;
    }

    public String getSourceFunction() {
        return this.sourceFunction;
    }

    public String getSourceFile() {
        return this.sourceFile;
    }

    public Integer getSourceLine() {
        return this.sourceLine;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Profiling (");

        sb.append(queryId);
        sb.append(", ").append(seq);
        sb.append(", ").append(state);
        sb.append(", ").append(duration);
        sb.append(", ").append(cpuUser);
        sb.append(", ").append(cpuSystem);
        sb.append(", ").append(contextVoluntary);
        sb.append(", ").append(contextInvoluntary);
        sb.append(", ").append(blockOpsIn);
        sb.append(", ").append(blockOpsOut);
        sb.append(", ").append(messagesSent);
        sb.append(", ").append(messagesReceived);
        sb.append(", ").append(pageFaultsMajor);
        sb.append(", ").append(pageFaultsMinor);
        sb.append(", ").append(swaps);
        sb.append(", ").append(sourceFunction);
        sb.append(", ").append(sourceFile);
        sb.append(", ").append(sourceLine);

        sb.append(")");
        return sb.toString();
    }
}
