/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines implements Serializable {

    private static final long serialVersionUID = -301726482;

    private final String    specificName;
    private final String    routineCatalog;
    private final String    routineSchema;
    private final String    routineName;
    private final String    routineType;
    private final String    dataType;
    private final Integer   characterMaximumLength;
    private final Integer   characterOctetLength;
    private final Integer   numericPrecision;
    private final Integer   numericScale;
    private final ULong     datetimePrecision;
    private final String    characterSetName;
    private final String    collationName;
    private final String    dtdIdentifier;
    private final String    routineBody;
    private final String    routineDefinition;
    private final String    externalName;
    private final String    externalLanguage;
    private final String    parameterStyle;
    private final String    isDeterministic;
    private final String    sqlDataAccess;
    private final String    sqlPath;
    private final String    securityType;
    private final Timestamp created;
    private final Timestamp lastAltered;
    private final String    sqlMode;
    private final String    routineComment;
    private final String    definer;
    private final String    characterSetClient;
    private final String    collationConnection;
    private final String    databaseCollation;

    public Routines(Routines value) {
        this.specificName = value.specificName;
        this.routineCatalog = value.routineCatalog;
        this.routineSchema = value.routineSchema;
        this.routineName = value.routineName;
        this.routineType = value.routineType;
        this.dataType = value.dataType;
        this.characterMaximumLength = value.characterMaximumLength;
        this.characterOctetLength = value.characterOctetLength;
        this.numericPrecision = value.numericPrecision;
        this.numericScale = value.numericScale;
        this.datetimePrecision = value.datetimePrecision;
        this.characterSetName = value.characterSetName;
        this.collationName = value.collationName;
        this.dtdIdentifier = value.dtdIdentifier;
        this.routineBody = value.routineBody;
        this.routineDefinition = value.routineDefinition;
        this.externalName = value.externalName;
        this.externalLanguage = value.externalLanguage;
        this.parameterStyle = value.parameterStyle;
        this.isDeterministic = value.isDeterministic;
        this.sqlDataAccess = value.sqlDataAccess;
        this.sqlPath = value.sqlPath;
        this.securityType = value.securityType;
        this.created = value.created;
        this.lastAltered = value.lastAltered;
        this.sqlMode = value.sqlMode;
        this.routineComment = value.routineComment;
        this.definer = value.definer;
        this.characterSetClient = value.characterSetClient;
        this.collationConnection = value.collationConnection;
        this.databaseCollation = value.databaseCollation;
    }

    public Routines(
        String    specificName,
        String    routineCatalog,
        String    routineSchema,
        String    routineName,
        String    routineType,
        String    dataType,
        Integer   characterMaximumLength,
        Integer   characterOctetLength,
        Integer   numericPrecision,
        Integer   numericScale,
        ULong     datetimePrecision,
        String    characterSetName,
        String    collationName,
        String    dtdIdentifier,
        String    routineBody,
        String    routineDefinition,
        String    externalName,
        String    externalLanguage,
        String    parameterStyle,
        String    isDeterministic,
        String    sqlDataAccess,
        String    sqlPath,
        String    securityType,
        Timestamp created,
        Timestamp lastAltered,
        String    sqlMode,
        String    routineComment,
        String    definer,
        String    characterSetClient,
        String    collationConnection,
        String    databaseCollation
    ) {
        this.specificName = specificName;
        this.routineCatalog = routineCatalog;
        this.routineSchema = routineSchema;
        this.routineName = routineName;
        this.routineType = routineType;
        this.dataType = dataType;
        this.characterMaximumLength = characterMaximumLength;
        this.characterOctetLength = characterOctetLength;
        this.numericPrecision = numericPrecision;
        this.numericScale = numericScale;
        this.datetimePrecision = datetimePrecision;
        this.characterSetName = characterSetName;
        this.collationName = collationName;
        this.dtdIdentifier = dtdIdentifier;
        this.routineBody = routineBody;
        this.routineDefinition = routineDefinition;
        this.externalName = externalName;
        this.externalLanguage = externalLanguage;
        this.parameterStyle = parameterStyle;
        this.isDeterministic = isDeterministic;
        this.sqlDataAccess = sqlDataAccess;
        this.sqlPath = sqlPath;
        this.securityType = securityType;
        this.created = created;
        this.lastAltered = lastAltered;
        this.sqlMode = sqlMode;
        this.routineComment = routineComment;
        this.definer = definer;
        this.characterSetClient = characterSetClient;
        this.collationConnection = collationConnection;
        this.databaseCollation = databaseCollation;
    }

    public String getSpecificName() {
        return this.specificName;
    }

    public String getRoutineCatalog() {
        return this.routineCatalog;
    }

    public String getRoutineSchema() {
        return this.routineSchema;
    }

    public String getRoutineName() {
        return this.routineName;
    }

    public String getRoutineType() {
        return this.routineType;
    }

    public String getDataType() {
        return this.dataType;
    }

    public Integer getCharacterMaximumLength() {
        return this.characterMaximumLength;
    }

    public Integer getCharacterOctetLength() {
        return this.characterOctetLength;
    }

    public Integer getNumericPrecision() {
        return this.numericPrecision;
    }

    public Integer getNumericScale() {
        return this.numericScale;
    }

    public ULong getDatetimePrecision() {
        return this.datetimePrecision;
    }

    public String getCharacterSetName() {
        return this.characterSetName;
    }

    public String getCollationName() {
        return this.collationName;
    }

    public String getDtdIdentifier() {
        return this.dtdIdentifier;
    }

    public String getRoutineBody() {
        return this.routineBody;
    }

    public String getRoutineDefinition() {
        return this.routineDefinition;
    }

    public String getExternalName() {
        return this.externalName;
    }

    public String getExternalLanguage() {
        return this.externalLanguage;
    }

    public String getParameterStyle() {
        return this.parameterStyle;
    }

    public String getIsDeterministic() {
        return this.isDeterministic;
    }

    public String getSqlDataAccess() {
        return this.sqlDataAccess;
    }

    public String getSqlPath() {
        return this.sqlPath;
    }

    public String getSecurityType() {
        return this.securityType;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public Timestamp getLastAltered() {
        return this.lastAltered;
    }

    public String getSqlMode() {
        return this.sqlMode;
    }

    public String getRoutineComment() {
        return this.routineComment;
    }

    public String getDefiner() {
        return this.definer;
    }

    public String getCharacterSetClient() {
        return this.characterSetClient;
    }

    public String getCollationConnection() {
        return this.collationConnection;
    }

    public String getDatabaseCollation() {
        return this.databaseCollation;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Routines (");

        sb.append(specificName);
        sb.append(", ").append(routineCatalog);
        sb.append(", ").append(routineSchema);
        sb.append(", ").append(routineName);
        sb.append(", ").append(routineType);
        sb.append(", ").append(dataType);
        sb.append(", ").append(characterMaximumLength);
        sb.append(", ").append(characterOctetLength);
        sb.append(", ").append(numericPrecision);
        sb.append(", ").append(numericScale);
        sb.append(", ").append(datetimePrecision);
        sb.append(", ").append(characterSetName);
        sb.append(", ").append(collationName);
        sb.append(", ").append(dtdIdentifier);
        sb.append(", ").append(routineBody);
        sb.append(", ").append(routineDefinition);
        sb.append(", ").append(externalName);
        sb.append(", ").append(externalLanguage);
        sb.append(", ").append(parameterStyle);
        sb.append(", ").append(isDeterministic);
        sb.append(", ").append(sqlDataAccess);
        sb.append(", ").append(sqlPath);
        sb.append(", ").append(securityType);
        sb.append(", ").append(created);
        sb.append(", ").append(lastAltered);
        sb.append(", ").append(sqlMode);
        sb.append(", ").append(routineComment);
        sb.append(", ").append(definer);
        sb.append(", ").append(characterSetClient);
        sb.append(", ").append(collationConnection);
        sb.append(", ").append(databaseCollation);

        sb.append(")");
        return sb.toString();
    }
}
