/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Statistics implements Serializable {

    private static final long serialVersionUID = 269969254;

    private final String tableCatalog;
    private final String tableSchema;
    private final String tableName;
    private final Long   nonUnique;
    private final String indexSchema;
    private final String indexName;
    private final Long   seqInIndex;
    private final String columnName;
    private final String collation;
    private final Long   cardinality;
    private final Long   subPart;
    private final String packed;
    private final String nullable;
    private final String indexType;
    private final String comment;
    private final String indexComment;

    public Statistics(Statistics value) {
        this.tableCatalog = value.tableCatalog;
        this.tableSchema = value.tableSchema;
        this.tableName = value.tableName;
        this.nonUnique = value.nonUnique;
        this.indexSchema = value.indexSchema;
        this.indexName = value.indexName;
        this.seqInIndex = value.seqInIndex;
        this.columnName = value.columnName;
        this.collation = value.collation;
        this.cardinality = value.cardinality;
        this.subPart = value.subPart;
        this.packed = value.packed;
        this.nullable = value.nullable;
        this.indexType = value.indexType;
        this.comment = value.comment;
        this.indexComment = value.indexComment;
    }

    public Statistics(
        String tableCatalog,
        String tableSchema,
        String tableName,
        Long   nonUnique,
        String indexSchema,
        String indexName,
        Long   seqInIndex,
        String columnName,
        String collation,
        Long   cardinality,
        Long   subPart,
        String packed,
        String nullable,
        String indexType,
        String comment,
        String indexComment
    ) {
        this.tableCatalog = tableCatalog;
        this.tableSchema = tableSchema;
        this.tableName = tableName;
        this.nonUnique = nonUnique;
        this.indexSchema = indexSchema;
        this.indexName = indexName;
        this.seqInIndex = seqInIndex;
        this.columnName = columnName;
        this.collation = collation;
        this.cardinality = cardinality;
        this.subPart = subPart;
        this.packed = packed;
        this.nullable = nullable;
        this.indexType = indexType;
        this.comment = comment;
        this.indexComment = indexComment;
    }

    public String getTableCatalog() {
        return this.tableCatalog;
    }

    public String getTableSchema() {
        return this.tableSchema;
    }

    public String getTableName() {
        return this.tableName;
    }

    public Long getNonUnique() {
        return this.nonUnique;
    }

    public String getIndexSchema() {
        return this.indexSchema;
    }

    public String getIndexName() {
        return this.indexName;
    }

    public Long getSeqInIndex() {
        return this.seqInIndex;
    }

    public String getColumnName() {
        return this.columnName;
    }

    public String getCollation() {
        return this.collation;
    }

    public Long getCardinality() {
        return this.cardinality;
    }

    public Long getSubPart() {
        return this.subPart;
    }

    public String getPacked() {
        return this.packed;
    }

    public String getNullable() {
        return this.nullable;
    }

    public String getIndexType() {
        return this.indexType;
    }

    public String getComment() {
        return this.comment;
    }

    public String getIndexComment() {
        return this.indexComment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Statistics (");

        sb.append(tableCatalog);
        sb.append(", ").append(tableSchema);
        sb.append(", ").append(tableName);
        sb.append(", ").append(nonUnique);
        sb.append(", ").append(indexSchema);
        sb.append(", ").append(indexName);
        sb.append(", ").append(seqInIndex);
        sb.append(", ").append(columnName);
        sb.append(", ").append(collation);
        sb.append(", ").append(cardinality);
        sb.append(", ").append(subPart);
        sb.append(", ").append(packed);
        sb.append(", ").append(nullable);
        sb.append(", ").append(indexType);
        sb.append(", ").append(comment);
        sb.append(", ").append(indexComment);

        sb.append(")");
        return sb.toString();
    }
}
