/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableStatistics implements Serializable {

    private static final long serialVersionUID = 1151112894;

    private final String tableSchema;
    private final String tableName;
    private final Long   rowsRead;
    private final Long   rowsChanged;
    private final Long   rowsChangedXIndexes;

    public TableStatistics(TableStatistics value) {
        this.tableSchema = value.tableSchema;
        this.tableName = value.tableName;
        this.rowsRead = value.rowsRead;
        this.rowsChanged = value.rowsChanged;
        this.rowsChangedXIndexes = value.rowsChangedXIndexes;
    }

    public TableStatistics(
        String tableSchema,
        String tableName,
        Long   rowsRead,
        Long   rowsChanged,
        Long   rowsChangedXIndexes
    ) {
        this.tableSchema = tableSchema;
        this.tableName = tableName;
        this.rowsRead = rowsRead;
        this.rowsChanged = rowsChanged;
        this.rowsChangedXIndexes = rowsChangedXIndexes;
    }

    public String getTableSchema() {
        return this.tableSchema;
    }

    public String getTableName() {
        return this.tableName;
    }

    public Long getRowsRead() {
        return this.rowsRead;
    }

    public Long getRowsChanged() {
        return this.rowsChanged;
    }

    public Long getRowsChangedXIndexes() {
        return this.rowsChangedXIndexes;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TableStatistics (");

        sb.append(tableSchema);
        sb.append(", ").append(tableName);
        sb.append(", ").append(rowsRead);
        sb.append(", ").append(rowsChanged);
        sb.append(", ").append(rowsChangedXIndexes);

        sb.append(")");
        return sb.toString();
    }
}
