/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableConstraints implements Serializable {

    private static final long serialVersionUID = 396433011;

    private final String constraintCatalog;
    private final String constraintSchema;
    private final String constraintName;
    private final String tableSchema;
    private final String tableName;
    private final String constraintType;

    public TableConstraints(TableConstraints value) {
        this.constraintCatalog = value.constraintCatalog;
        this.constraintSchema = value.constraintSchema;
        this.constraintName = value.constraintName;
        this.tableSchema = value.tableSchema;
        this.tableName = value.tableName;
        this.constraintType = value.constraintType;
    }

    public TableConstraints(
        String constraintCatalog,
        String constraintSchema,
        String constraintName,
        String tableSchema,
        String tableName,
        String constraintType
    ) {
        this.constraintCatalog = constraintCatalog;
        this.constraintSchema = constraintSchema;
        this.constraintName = constraintName;
        this.tableSchema = tableSchema;
        this.tableName = tableName;
        this.constraintType = constraintType;
    }

    public String getConstraintCatalog() {
        return this.constraintCatalog;
    }

    public String getConstraintSchema() {
        return this.constraintSchema;
    }

    public String getConstraintName() {
        return this.constraintName;
    }

    public String getTableSchema() {
        return this.tableSchema;
    }

    public String getTableName() {
        return this.tableName;
    }

    public String getConstraintType() {
        return this.constraintType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TableConstraints (");

        sb.append(constraintCatalog);
        sb.append(", ").append(constraintSchema);
        sb.append(", ").append(constraintName);
        sb.append(", ").append(tableSchema);
        sb.append(", ").append(tableName);
        sb.append(", ").append(constraintType);

        sb.append(")");
        return sb.toString();
    }
}
