/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables implements Serializable {

    private static final long serialVersionUID = -86709304;

    private final String    tableCatalog;
    private final String    tableSchema;
    private final String    tableName;
    private final String    tableType;
    private final String    engine;
    private final ULong     version;
    private final String    rowFormat;
    private final ULong     tableRows;
    private final ULong     avgRowLength;
    private final ULong     dataLength;
    private final ULong     maxDataLength;
    private final ULong     indexLength;
    private final ULong     dataFree;
    private final ULong     autoIncrement;
    private final Timestamp createTime;
    private final Timestamp updateTime;
    private final Timestamp checkTime;
    private final String    tableCollation;
    private final ULong     checksum;
    private final String    createOptions;
    private final String    tableComment;

    public Tables(Tables value) {
        this.tableCatalog = value.tableCatalog;
        this.tableSchema = value.tableSchema;
        this.tableName = value.tableName;
        this.tableType = value.tableType;
        this.engine = value.engine;
        this.version = value.version;
        this.rowFormat = value.rowFormat;
        this.tableRows = value.tableRows;
        this.avgRowLength = value.avgRowLength;
        this.dataLength = value.dataLength;
        this.maxDataLength = value.maxDataLength;
        this.indexLength = value.indexLength;
        this.dataFree = value.dataFree;
        this.autoIncrement = value.autoIncrement;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.checkTime = value.checkTime;
        this.tableCollation = value.tableCollation;
        this.checksum = value.checksum;
        this.createOptions = value.createOptions;
        this.tableComment = value.tableComment;
    }

    public Tables(
        String    tableCatalog,
        String    tableSchema,
        String    tableName,
        String    tableType,
        String    engine,
        ULong     version,
        String    rowFormat,
        ULong     tableRows,
        ULong     avgRowLength,
        ULong     dataLength,
        ULong     maxDataLength,
        ULong     indexLength,
        ULong     dataFree,
        ULong     autoIncrement,
        Timestamp createTime,
        Timestamp updateTime,
        Timestamp checkTime,
        String    tableCollation,
        ULong     checksum,
        String    createOptions,
        String    tableComment
    ) {
        this.tableCatalog = tableCatalog;
        this.tableSchema = tableSchema;
        this.tableName = tableName;
        this.tableType = tableType;
        this.engine = engine;
        this.version = version;
        this.rowFormat = rowFormat;
        this.tableRows = tableRows;
        this.avgRowLength = avgRowLength;
        this.dataLength = dataLength;
        this.maxDataLength = maxDataLength;
        this.indexLength = indexLength;
        this.dataFree = dataFree;
        this.autoIncrement = autoIncrement;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.checkTime = checkTime;
        this.tableCollation = tableCollation;
        this.checksum = checksum;
        this.createOptions = createOptions;
        this.tableComment = tableComment;
    }

    public String getTableCatalog() {
        return this.tableCatalog;
    }

    public String getTableSchema() {
        return this.tableSchema;
    }

    public String getTableName() {
        return this.tableName;
    }

    public String getTableType() {
        return this.tableType;
    }

    public String getEngine() {
        return this.engine;
    }

    public ULong getVersion() {
        return this.version;
    }

    public String getRowFormat() {
        return this.rowFormat;
    }

    public ULong getTableRows() {
        return this.tableRows;
    }

    public ULong getAvgRowLength() {
        return this.avgRowLength;
    }

    public ULong getDataLength() {
        return this.dataLength;
    }

    public ULong getMaxDataLength() {
        return this.maxDataLength;
    }

    public ULong getIndexLength() {
        return this.indexLength;
    }

    public ULong getDataFree() {
        return this.dataFree;
    }

    public ULong getAutoIncrement() {
        return this.autoIncrement;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public Timestamp getCheckTime() {
        return this.checkTime;
    }

    public String getTableCollation() {
        return this.tableCollation;
    }

    public ULong getChecksum() {
        return this.checksum;
    }

    public String getCreateOptions() {
        return this.createOptions;
    }

    public String getTableComment() {
        return this.tableComment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tables (");

        sb.append(tableCatalog);
        sb.append(", ").append(tableSchema);
        sb.append(", ").append(tableName);
        sb.append(", ").append(tableType);
        sb.append(", ").append(engine);
        sb.append(", ").append(version);
        sb.append(", ").append(rowFormat);
        sb.append(", ").append(tableRows);
        sb.append(", ").append(avgRowLength);
        sb.append(", ").append(dataLength);
        sb.append(", ").append(maxDataLength);
        sb.append(", ").append(indexLength);
        sb.append(", ").append(dataFree);
        sb.append(", ").append(autoIncrement);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(checkTime);
        sb.append(", ").append(tableCollation);
        sb.append(", ").append(checksum);
        sb.append(", ").append(createOptions);
        sb.append(", ").append(tableComment);

        sb.append(")");
        return sb.toString();
    }
}
