/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tablespaces implements Serializable {

    private static final long serialVersionUID = -2024874681;

    private final String tablespaceName;
    private final String engine;
    private final String tablespaceType;
    private final String logfileGroupName;
    private final ULong  extentSize;
    private final ULong  autoextendSize;
    private final ULong  maximumSize;
    private final ULong  nodegroupId;
    private final String tablespaceComment;

    public Tablespaces(Tablespaces value) {
        this.tablespaceName = value.tablespaceName;
        this.engine = value.engine;
        this.tablespaceType = value.tablespaceType;
        this.logfileGroupName = value.logfileGroupName;
        this.extentSize = value.extentSize;
        this.autoextendSize = value.autoextendSize;
        this.maximumSize = value.maximumSize;
        this.nodegroupId = value.nodegroupId;
        this.tablespaceComment = value.tablespaceComment;
    }

    public Tablespaces(
        String tablespaceName,
        String engine,
        String tablespaceType,
        String logfileGroupName,
        ULong  extentSize,
        ULong  autoextendSize,
        ULong  maximumSize,
        ULong  nodegroupId,
        String tablespaceComment
    ) {
        this.tablespaceName = tablespaceName;
        this.engine = engine;
        this.tablespaceType = tablespaceType;
        this.logfileGroupName = logfileGroupName;
        this.extentSize = extentSize;
        this.autoextendSize = autoextendSize;
        this.maximumSize = maximumSize;
        this.nodegroupId = nodegroupId;
        this.tablespaceComment = tablespaceComment;
    }

    public String getTablespaceName() {
        return this.tablespaceName;
    }

    public String getEngine() {
        return this.engine;
    }

    public String getTablespaceType() {
        return this.tablespaceType;
    }

    public String getLogfileGroupName() {
        return this.logfileGroupName;
    }

    public ULong getExtentSize() {
        return this.extentSize;
    }

    public ULong getAutoextendSize() {
        return this.autoextendSize;
    }

    public ULong getMaximumSize() {
        return this.maximumSize;
    }

    public ULong getNodegroupId() {
        return this.nodegroupId;
    }

    public String getTablespaceComment() {
        return this.tablespaceComment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tablespaces (");

        sb.append(tablespaceName);
        sb.append(", ").append(engine);
        sb.append(", ").append(tablespaceType);
        sb.append(", ").append(logfileGroupName);
        sb.append(", ").append(extentSize);
        sb.append(", ").append(autoextendSize);
        sb.append(", ").append(maximumSize);
        sb.append(", ").append(nodegroupId);
        sb.append(", ").append(tablespaceComment);

        sb.append(")");
        return sb.toString();
    }
}
