/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPrivileges implements Serializable {

    private static final long serialVersionUID = 146467641;

    private final String grantee;
    private final String tableCatalog;
    private final String privilegeType;
    private final String isGrantable;

    public UserPrivileges(UserPrivileges value) {
        this.grantee = value.grantee;
        this.tableCatalog = value.tableCatalog;
        this.privilegeType = value.privilegeType;
        this.isGrantable = value.isGrantable;
    }

    public UserPrivileges(
        String grantee,
        String tableCatalog,
        String privilegeType,
        String isGrantable
    ) {
        this.grantee = grantee;
        this.tableCatalog = tableCatalog;
        this.privilegeType = privilegeType;
        this.isGrantable = isGrantable;
    }

    public String getGrantee() {
        return this.grantee;
    }

    public String getTableCatalog() {
        return this.tableCatalog;
    }

    public String getPrivilegeType() {
        return this.privilegeType;
    }

    public String getIsGrantable() {
        return this.isGrantable;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPrivileges (");

        sb.append(grantee);
        sb.append(", ").append(tableCatalog);
        sb.append(", ").append(privilegeType);
        sb.append(", ").append(isGrantable);

        sb.append(")");
        return sb.toString();
    }
}
