/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XtradbRseg implements Serializable {

    private static final long serialVersionUID = 1434723988;

    private final ULong rsegId;
    private final ULong spaceId;
    private final ULong zipSize;
    private final ULong pageNo;
    private final ULong maxSize;
    private final ULong currSize;

    public XtradbRseg(XtradbRseg value) {
        this.rsegId = value.rsegId;
        this.spaceId = value.spaceId;
        this.zipSize = value.zipSize;
        this.pageNo = value.pageNo;
        this.maxSize = value.maxSize;
        this.currSize = value.currSize;
    }

    public XtradbRseg(
        ULong rsegId,
        ULong spaceId,
        ULong zipSize,
        ULong pageNo,
        ULong maxSize,
        ULong currSize
    ) {
        this.rsegId = rsegId;
        this.spaceId = spaceId;
        this.zipSize = zipSize;
        this.pageNo = pageNo;
        this.maxSize = maxSize;
        this.currSize = currSize;
    }

    public ULong getRsegId() {
        return this.rsegId;
    }

    public ULong getSpaceId() {
        return this.spaceId;
    }

    public ULong getZipSize() {
        return this.zipSize;
    }

    public ULong getPageNo() {
        return this.pageNo;
    }

    public ULong getMaxSize() {
        return this.maxSize;
    }

    public ULong getCurrSize() {
        return this.currSize;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("XtradbRseg (");

        sb.append(rsegId);
        sb.append(", ").append(spaceId);
        sb.append(", ").append(zipSize);
        sb.append(", ").append(pageNo);
        sb.append(", ").append(maxSize);
        sb.append(", ").append(currSize);

        sb.append(")");
        return sb.toString();
    }
}
