/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XtradbReadView implements Serializable {

    private static final long serialVersionUID = 2001781642;

    private final ULong  readViewUndoNumber;
    private final String readViewLowLimitTrxNumber;
    private final String readViewUpperLimitTrxId;
    private final String readViewLowLimitTrxId;

    public XtradbReadView(XtradbReadView value) {
        this.readViewUndoNumber = value.readViewUndoNumber;
        this.readViewLowLimitTrxNumber = value.readViewLowLimitTrxNumber;
        this.readViewUpperLimitTrxId = value.readViewUpperLimitTrxId;
        this.readViewLowLimitTrxId = value.readViewLowLimitTrxId;
    }

    public XtradbReadView(
        ULong  readViewUndoNumber,
        String readViewLowLimitTrxNumber,
        String readViewUpperLimitTrxId,
        String readViewLowLimitTrxId
    ) {
        this.readViewUndoNumber = readViewUndoNumber;
        this.readViewLowLimitTrxNumber = readViewLowLimitTrxNumber;
        this.readViewUpperLimitTrxId = readViewUpperLimitTrxId;
        this.readViewLowLimitTrxId = readViewLowLimitTrxId;
    }

    public ULong getReadViewUndoNumber() {
        return this.readViewUndoNumber;
    }

    public String getReadViewLowLimitTrxNumber() {
        return this.readViewLowLimitTrxNumber;
    }

    public String getReadViewUpperLimitTrxId() {
        return this.readViewUpperLimitTrxId;
    }

    public String getReadViewLowLimitTrxId() {
        return this.readViewLowLimitTrxId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("XtradbReadView (");

        sb.append(readViewUndoNumber);
        sb.append(", ").append(readViewLowLimitTrxNumber);
        sb.append(", ").append(readViewUpperLimitTrxId);
        sb.append(", ").append(readViewLowLimitTrxId);

        sb.append(")");
        return sb.toString();
    }
}
