/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.records;


import com.johnsong.android.spring.jooq.information_schema.tables.Routines;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutinesRecord extends TableRecordImpl<RoutinesRecord> {

    private static final long serialVersionUID = -60400038;

    /**
     * Setter for <code>information_schema.ROUTINES.SPECIFIC_NAME</code>.
     */
    public RoutinesRecord setSpecificName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.SPECIFIC_NAME</code>.
     */
    public String getSpecificName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.ROUTINE_CATALOG</code>.
     */
    public RoutinesRecord setRoutineCatalog(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.ROUTINE_CATALOG</code>.
     */
    public String getRoutineCatalog() {
        return (String) get(1);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.ROUTINE_SCHEMA</code>.
     */
    public RoutinesRecord setRoutineSchema(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.ROUTINE_SCHEMA</code>.
     */
    public String getRoutineSchema() {
        return (String) get(2);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.ROUTINE_NAME</code>.
     */
    public RoutinesRecord setRoutineName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.ROUTINE_NAME</code>.
     */
    public String getRoutineName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.ROUTINE_TYPE</code>.
     */
    public RoutinesRecord setRoutineType(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.ROUTINE_TYPE</code>.
     */
    public String getRoutineType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.DATA_TYPE</code>.
     */
    public RoutinesRecord setDataType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.DATA_TYPE</code>.
     */
    public String getDataType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.CHARACTER_MAXIMUM_LENGTH</code>.
     */
    public RoutinesRecord setCharacterMaximumLength(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.CHARACTER_MAXIMUM_LENGTH</code>.
     */
    public Integer getCharacterMaximumLength() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.CHARACTER_OCTET_LENGTH</code>.
     */
    public RoutinesRecord setCharacterOctetLength(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.CHARACTER_OCTET_LENGTH</code>.
     */
    public Integer getCharacterOctetLength() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.NUMERIC_PRECISION</code>.
     */
    public RoutinesRecord setNumericPrecision(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.NUMERIC_PRECISION</code>.
     */
    public Integer getNumericPrecision() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.NUMERIC_SCALE</code>.
     */
    public RoutinesRecord setNumericScale(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.NUMERIC_SCALE</code>.
     */
    public Integer getNumericScale() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.DATETIME_PRECISION</code>.
     */
    public RoutinesRecord setDatetimePrecision(ULong value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.DATETIME_PRECISION</code>.
     */
    public ULong getDatetimePrecision() {
        return (ULong) get(10);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.CHARACTER_SET_NAME</code>.
     */
    public RoutinesRecord setCharacterSetName(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.CHARACTER_SET_NAME</code>.
     */
    public String getCharacterSetName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.COLLATION_NAME</code>.
     */
    public RoutinesRecord setCollationName(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.COLLATION_NAME</code>.
     */
    public String getCollationName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.DTD_IDENTIFIER</code>.
     */
    public RoutinesRecord setDtdIdentifier(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.DTD_IDENTIFIER</code>.
     */
    public String getDtdIdentifier() {
        return (String) get(13);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.ROUTINE_BODY</code>.
     */
    public RoutinesRecord setRoutineBody(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.ROUTINE_BODY</code>.
     */
    public String getRoutineBody() {
        return (String) get(14);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.ROUTINE_DEFINITION</code>.
     */
    public RoutinesRecord setRoutineDefinition(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.ROUTINE_DEFINITION</code>.
     */
    public String getRoutineDefinition() {
        return (String) get(15);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.EXTERNAL_NAME</code>.
     */
    public RoutinesRecord setExternalName(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.EXTERNAL_NAME</code>.
     */
    public String getExternalName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.EXTERNAL_LANGUAGE</code>.
     */
    public RoutinesRecord setExternalLanguage(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.EXTERNAL_LANGUAGE</code>.
     */
    public String getExternalLanguage() {
        return (String) get(17);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.PARAMETER_STYLE</code>.
     */
    public RoutinesRecord setParameterStyle(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.PARAMETER_STYLE</code>.
     */
    public String getParameterStyle() {
        return (String) get(18);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.IS_DETERMINISTIC</code>.
     */
    public RoutinesRecord setIsDeterministic(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.IS_DETERMINISTIC</code>.
     */
    public String getIsDeterministic() {
        return (String) get(19);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.SQL_DATA_ACCESS</code>.
     */
    public RoutinesRecord setSqlDataAccess(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.SQL_DATA_ACCESS</code>.
     */
    public String getSqlDataAccess() {
        return (String) get(20);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.SQL_PATH</code>.
     */
    public RoutinesRecord setSqlPath(String value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.SQL_PATH</code>.
     */
    public String getSqlPath() {
        return (String) get(21);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.SECURITY_TYPE</code>.
     */
    public RoutinesRecord setSecurityType(String value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.SECURITY_TYPE</code>.
     */
    public String getSecurityType() {
        return (String) get(22);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.CREATED</code>.
     */
    public RoutinesRecord setCreated(Timestamp value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.CREATED</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(23);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.LAST_ALTERED</code>.
     */
    public RoutinesRecord setLastAltered(Timestamp value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.LAST_ALTERED</code>.
     */
    public Timestamp getLastAltered() {
        return (Timestamp) get(24);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.SQL_MODE</code>.
     */
    public RoutinesRecord setSqlMode(String value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.SQL_MODE</code>.
     */
    public String getSqlMode() {
        return (String) get(25);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.ROUTINE_COMMENT</code>.
     */
    public RoutinesRecord setRoutineComment(String value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.ROUTINE_COMMENT</code>.
     */
    public String getRoutineComment() {
        return (String) get(26);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.DEFINER</code>.
     */
    public RoutinesRecord setDefiner(String value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.DEFINER</code>.
     */
    public String getDefiner() {
        return (String) get(27);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.CHARACTER_SET_CLIENT</code>.
     */
    public RoutinesRecord setCharacterSetClient(String value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.CHARACTER_SET_CLIENT</code>.
     */
    public String getCharacterSetClient() {
        return (String) get(28);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.COLLATION_CONNECTION</code>.
     */
    public RoutinesRecord setCollationConnection(String value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.COLLATION_CONNECTION</code>.
     */
    public String getCollationConnection() {
        return (String) get(29);
    }

    /**
     * Setter for <code>information_schema.ROUTINES.DATABASE_COLLATION</code>.
     */
    public RoutinesRecord setDatabaseCollation(String value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.ROUTINES.DATABASE_COLLATION</code>.
     */
    public String getDatabaseCollation() {
        return (String) get(30);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoutinesRecord
     */
    public RoutinesRecord() {
        super(Routines.ROUTINES);
    }

    /**
     * Create a detached, initialised RoutinesRecord
     */
    public RoutinesRecord(String specificName, String routineCatalog, String routineSchema, String routineName, String routineType, String dataType, Integer characterMaximumLength, Integer characterOctetLength, Integer numericPrecision, Integer numericScale, ULong datetimePrecision, String characterSetName, String collationName, String dtdIdentifier, String routineBody, String routineDefinition, String externalName, String externalLanguage, String parameterStyle, String isDeterministic, String sqlDataAccess, String sqlPath, String securityType, Timestamp created, Timestamp lastAltered, String sqlMode, String routineComment, String definer, String characterSetClient, String collationConnection, String databaseCollation) {
        super(Routines.ROUTINES);

        set(0, specificName);
        set(1, routineCatalog);
        set(2, routineSchema);
        set(3, routineName);
        set(4, routineType);
        set(5, dataType);
        set(6, characterMaximumLength);
        set(7, characterOctetLength);
        set(8, numericPrecision);
        set(9, numericScale);
        set(10, datetimePrecision);
        set(11, characterSetName);
        set(12, collationName);
        set(13, dtdIdentifier);
        set(14, routineBody);
        set(15, routineDefinition);
        set(16, externalName);
        set(17, externalLanguage);
        set(18, parameterStyle);
        set(19, isDeterministic);
        set(20, sqlDataAccess);
        set(21, sqlPath);
        set(22, securityType);
        set(23, created);
        set(24, lastAltered);
        set(25, sqlMode);
        set(26, routineComment);
        set(27, definer);
        set(28, characterSetClient);
        set(29, collationConnection);
        set(30, databaseCollation);
    }
}
