/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.records;


import com.johnsong.android.spring.jooq.information_schema.tables.XtradbReadView;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XtradbReadViewRecord extends TableRecordImpl<XtradbReadViewRecord> implements Record4<ULong, String, String, String> {

    private static final long serialVersionUID = -475343200;

    /**
     * Setter for <code>information_schema.XTRADB_READ_VIEW.READ_VIEW_UNDO_NUMBER</code>.
     */
    public XtradbReadViewRecord setReadViewUndoNumber(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.XTRADB_READ_VIEW.READ_VIEW_UNDO_NUMBER</code>.
     */
    public ULong getReadViewUndoNumber() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>information_schema.XTRADB_READ_VIEW.READ_VIEW_LOW_LIMIT_TRX_NUMBER</code>.
     */
    public XtradbReadViewRecord setReadViewLowLimitTrxNumber(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.XTRADB_READ_VIEW.READ_VIEW_LOW_LIMIT_TRX_NUMBER</code>.
     */
    public String getReadViewLowLimitTrxNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>information_schema.XTRADB_READ_VIEW.READ_VIEW_UPPER_LIMIT_TRX_ID</code>.
     */
    public XtradbReadViewRecord setReadViewUpperLimitTrxId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.XTRADB_READ_VIEW.READ_VIEW_UPPER_LIMIT_TRX_ID</code>.
     */
    public String getReadViewUpperLimitTrxId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>information_schema.XTRADB_READ_VIEW.READ_VIEW_LOW_LIMIT_TRX_ID</code>.
     */
    public XtradbReadViewRecord setReadViewLowLimitTrxId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.XTRADB_READ_VIEW.READ_VIEW_LOW_LIMIT_TRX_ID</code>.
     */
    public String getReadViewLowLimitTrxId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<ULong, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<ULong, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return XtradbReadView.XTRADB_READ_VIEW.READ_VIEW_UNDO_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return XtradbReadView.XTRADB_READ_VIEW.READ_VIEW_LOW_LIMIT_TRX_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return XtradbReadView.XTRADB_READ_VIEW.READ_VIEW_UPPER_LIMIT_TRX_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return XtradbReadView.XTRADB_READ_VIEW.READ_VIEW_LOW_LIMIT_TRX_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getReadViewUndoNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReadViewLowLimitTrxNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getReadViewUpperLimitTrxId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getReadViewLowLimitTrxId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getReadViewUndoNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReadViewLowLimitTrxNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getReadViewUpperLimitTrxId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReadViewLowLimitTrxId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbReadViewRecord value1(ULong value) {
        setReadViewUndoNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbReadViewRecord value2(String value) {
        setReadViewLowLimitTrxNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbReadViewRecord value3(String value) {
        setReadViewUpperLimitTrxId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbReadViewRecord value4(String value) {
        setReadViewLowLimitTrxId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbReadViewRecord values(ULong value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached XtradbReadViewRecord
     */
    public XtradbReadViewRecord() {
        super(XtradbReadView.XTRADB_READ_VIEW);
    }

    /**
     * Create a detached, initialised XtradbReadViewRecord
     */
    public XtradbReadViewRecord(ULong readViewUndoNumber, String readViewLowLimitTrxNumber, String readViewUpperLimitTrxId, String readViewLowLimitTrxId) {
        super(XtradbReadView.XTRADB_READ_VIEW);

        set(0, readViewUndoNumber);
        set(1, readViewLowLimitTrxNumber);
        set(2, readViewUpperLimitTrxId);
        set(3, readViewLowLimitTrxId);
    }
}
