/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.information_schema.tables.records;


import com.johnsong.android.spring.jooq.information_schema.tables.XtradbRseg;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XtradbRsegRecord extends TableRecordImpl<XtradbRsegRecord> implements Record6<ULong, ULong, ULong, ULong, ULong, ULong> {

    private static final long serialVersionUID = 1347456742;

    /**
     * Setter for <code>information_schema.XTRADB_RSEG.rseg_id</code>.
     */
    public XtradbRsegRecord setRsegId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.XTRADB_RSEG.rseg_id</code>.
     */
    public ULong getRsegId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>information_schema.XTRADB_RSEG.space_id</code>.
     */
    public XtradbRsegRecord setSpaceId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.XTRADB_RSEG.space_id</code>.
     */
    public ULong getSpaceId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>information_schema.XTRADB_RSEG.zip_size</code>.
     */
    public XtradbRsegRecord setZipSize(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.XTRADB_RSEG.zip_size</code>.
     */
    public ULong getZipSize() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>information_schema.XTRADB_RSEG.page_no</code>.
     */
    public XtradbRsegRecord setPageNo(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.XTRADB_RSEG.page_no</code>.
     */
    public ULong getPageNo() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>information_schema.XTRADB_RSEG.max_size</code>.
     */
    public XtradbRsegRecord setMaxSize(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.XTRADB_RSEG.max_size</code>.
     */
    public ULong getMaxSize() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>information_schema.XTRADB_RSEG.curr_size</code>.
     */
    public XtradbRsegRecord setCurrSize(ULong value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>information_schema.XTRADB_RSEG.curr_size</code>.
     */
    public ULong getCurrSize() {
        return (ULong) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<ULong, ULong, ULong, ULong, ULong, ULong> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<ULong, ULong, ULong, ULong, ULong, ULong> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return XtradbRseg.XTRADB_RSEG.RSEG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return XtradbRseg.XTRADB_RSEG.SPACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return XtradbRseg.XTRADB_RSEG.ZIP_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field4() {
        return XtradbRseg.XTRADB_RSEG.PAGE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field5() {
        return XtradbRseg.XTRADB_RSEG.MAX_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field6() {
        return XtradbRseg.XTRADB_RSEG.CURR_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getRsegId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component2() {
        return getSpaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component3() {
        return getZipSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component4() {
        return getPageNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component5() {
        return getMaxSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component6() {
        return getCurrSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getRsegId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getSpaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getZipSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value4() {
        return getPageNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value5() {
        return getMaxSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value6() {
        return getCurrSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbRsegRecord value1(ULong value) {
        setRsegId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbRsegRecord value2(ULong value) {
        setSpaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbRsegRecord value3(ULong value) {
        setZipSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbRsegRecord value4(ULong value) {
        setPageNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbRsegRecord value5(ULong value) {
        setMaxSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbRsegRecord value6(ULong value) {
        setCurrSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XtradbRsegRecord values(ULong value1, ULong value2, ULong value3, ULong value4, ULong value5, ULong value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached XtradbRsegRecord
     */
    public XtradbRsegRecord() {
        super(XtradbRseg.XTRADB_RSEG);
    }

    /**
     * Create a detached, initialised XtradbRsegRecord
     */
    public XtradbRsegRecord(ULong rsegId, ULong spaceId, ULong zipSize, ULong pageNo, ULong maxSize, ULong currSize) {
        super(XtradbRseg.XTRADB_RSEG);

        set(0, rsegId);
        set(1, spaceId);
        set(2, zipSize);
        set(3, pageNo);
        set(4, maxSize);
        set(5, currSize);
    }
}
