/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq;


import com.johnsong.android.spring.jooq.tables.City;
import com.johnsong.android.spring.jooq.tables.FlywaySchemaHistory;
import com.johnsong.android.spring.jooq.tables.Foodcategory;
import com.johnsong.android.spring.jooq.tables.Region;
import com.johnsong.android.spring.jooq.tables.Storesummary;
import com.johnsong.android.spring.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Banana extends SchemaImpl {

    private static final long serialVersionUID = 1609043629;

    /**
     * The reference instance of <code>banana</code>
     */
    public static final Banana BANANA = new Banana();

    /**
     * The table <code>banana.City</code>.
     */
    public final City CITY = com.johnsong.android.spring.jooq.tables.City.CITY;

    /**
     * The table <code>banana.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.johnsong.android.spring.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>banana.FoodCategory</code>.
     */
    public final Foodcategory FOODCATEGORY = com.johnsong.android.spring.jooq.tables.Foodcategory.FOODCATEGORY;

    /**
     * The table <code>banana.Region</code>.
     */
    public final Region REGION = com.johnsong.android.spring.jooq.tables.Region.REGION;

    /**
     * The table <code>banana.StoreSummary</code>.
     */
    public final Storesummary STORESUMMARY = com.johnsong.android.spring.jooq.tables.Storesummary.STORESUMMARY;

    /**
     * The table <code>banana.User</code>.
     */
    public final User USER = com.johnsong.android.spring.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Banana() {
        super("banana", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            City.CITY,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Foodcategory.FOODCATEGORY,
            Region.REGION,
            Storesummary.STORESUMMARY,
            User.USER);
    }
}
