/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.jooq.tables.records;


import com.johnsong.android.jooq.tables.Storesummary;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoresummaryRecord extends TableRecordImpl<StoresummaryRecord> implements Record10<Integer, String, String, Double, Double, Integer, Integer, Double, Integer, Integer> {

    private static final long serialVersionUID = -437414868;

    /**
     * Setter for <code>banana.StoreSummary.store_id</code>.
     */
    public StoresummaryRecord setStoreId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>banana.StoreSummary.store_id</code>.
     */
    public Integer getStoreId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>banana.StoreSummary.name</code>.
     */
    public StoresummaryRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>banana.StoreSummary.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>banana.StoreSummary.img</code>.
     */
    public StoresummaryRecord setImg(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>banana.StoreSummary.img</code>.
     */
    public String getImg() {
        return (String) get(2);
    }

    /**
     * Setter for <code>banana.StoreSummary.lat</code>.
     */
    public StoresummaryRecord setLat(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>banana.StoreSummary.lat</code>.
     */
    public Double getLat() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>banana.StoreSummary.lon</code>.
     */
    public StoresummaryRecord setLon(Double value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>banana.StoreSummary.lon</code>.
     */
    public Double getLon() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>banana.StoreSummary.hit</code>.
     */
    public StoresummaryRecord setHit(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>banana.StoreSummary.hit</code>.
     */
    public Integer getHit() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>banana.StoreSummary.review_count</code>.
     */
    public StoresummaryRecord setReviewCount(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>banana.StoreSummary.review_count</code>.
     */
    public Integer getReviewCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>banana.StoreSummary.score</code>.
     */
    public StoresummaryRecord setScore(Double value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>banana.StoreSummary.score</code>.
     */
    public Double getScore() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>banana.StoreSummary.region_id</code>.
     */
    public StoresummaryRecord setRegionId(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>banana.StoreSummary.region_id</code>.
     */
    public Integer getRegionId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>banana.StoreSummary.food_category_id</code>.
     */
    public StoresummaryRecord setFoodCategoryId(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>banana.StoreSummary.food_category_id</code>.
     */
    public Integer getFoodCategoryId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Double, Double, Integer, Integer, Double, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Double, Double, Integer, Integer, Double, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Storesummary.STORESUMMARY.STORE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Storesummary.STORESUMMARY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Storesummary.STORESUMMARY.IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Storesummary.STORESUMMARY.LAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Storesummary.STORESUMMARY.LON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Storesummary.STORESUMMARY.HIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Storesummary.STORESUMMARY.REVIEW_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return Storesummary.STORESUMMARY.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Storesummary.STORESUMMARY.REGION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Storesummary.STORESUMMARY.FOOD_CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStoreId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getLon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getHit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getReviewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getFoodCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStoreId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getLon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getHit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getReviewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getFoodCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord value1(Integer value) {
        setStoreId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord value3(String value) {
        setImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord value4(Double value) {
        setLat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord value5(Double value) {
        setLon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord value6(Integer value) {
        setHit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord value7(Integer value) {
        setReviewCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord value8(Double value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord value9(Integer value) {
        setRegionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord value10(Integer value) {
        setFoodCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoresummaryRecord values(Integer value1, String value2, String value3, Double value4, Double value5, Integer value6, Integer value7, Double value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoresummaryRecord
     */
    public StoresummaryRecord() {
        super(Storesummary.STORESUMMARY);
    }

    /**
     * Create a detached, initialised StoresummaryRecord
     */
    public StoresummaryRecord(Integer storeId, String name, String img, Double lat, Double lon, Integer hit, Integer reviewCount, Double score, Integer regionId, Integer foodCategoryId) {
        super(Storesummary.STORESUMMARY);

        set(0, storeId);
        set(1, name);
        set(2, img);
        set(3, lat);
        set(4, lon);
        set(5, hit);
        set(6, reviewCount);
        set(7, score);
        set(8, regionId);
        set(9, foodCategoryId);
    }
}
