/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.banana.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City implements Serializable {

    private static final long serialVersionUID = -1538149029;

    private final Integer cityId;
    private final String  cityName;

    public City(City value) {
        this.cityId = value.cityId;
        this.cityName = value.cityName;
    }

    public City(
        Integer cityId,
        String  cityName
    ) {
        this.cityId = cityId;
        this.cityName = cityName;
    }

    public Integer getCityId() {
        return this.cityId;
    }

    public String getCityName() {
        return this.cityName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("City (");

        sb.append(cityId);
        sb.append(", ").append(cityName);

        sb.append(")");
        return sb.toString();
    }
}
