/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.banana.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Foodcategory implements Serializable {

    private static final long serialVersionUID = 1095083360;

    private final Integer foodCategoryId;
    private final String  titme;

    public Foodcategory(Foodcategory value) {
        this.foodCategoryId = value.foodCategoryId;
        this.titme = value.titme;
    }

    public Foodcategory(
        Integer foodCategoryId,
        String  titme
    ) {
        this.foodCategoryId = foodCategoryId;
        this.titme = titme;
    }

    public Integer getFoodCategoryId() {
        return this.foodCategoryId;
    }

    public String getTitme() {
        return this.titme;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Foodcategory (");

        sb.append(foodCategoryId);
        sb.append(", ").append(titme);

        sb.append(")");
        return sb.toString();
    }
}
