/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.banana.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -108366703;

    private final Integer userId;
    private final String  email;
    private final String  loginPlatform;
    private final String  picture;
    private final String  name;

    public User(User value) {
        this.userId = value.userId;
        this.email = value.email;
        this.loginPlatform = value.loginPlatform;
        this.picture = value.picture;
        this.name = value.name;
    }

    public User(
        Integer userId,
        String  email,
        String  loginPlatform,
        String  picture,
        String  name
    ) {
        this.userId = userId;
        this.email = email;
        this.loginPlatform = loginPlatform;
        this.picture = picture;
        this.name = name;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public String getEmail() {
        return this.email;
    }

    public String getLoginPlatform() {
        return this.loginPlatform;
    }

    public String getPicture() {
        return this.picture;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(email);
        sb.append(", ").append(loginPlatform);
        sb.append(", ").append(picture);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
