/*
 * This file is generated by jOOQ.
*/
package com.johnsong.android.spring.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Storesummary implements Serializable {

    private static final long serialVersionUID = 1517798320;

    private final Integer storeId;
    private final String  name;
    private final String  img;
    private final Double  lat;
    private final Double  lon;
    private final Integer hit;
    private final Integer reviewCount;
    private final Double  score;
    private final Integer regionId;
    private final Integer foodCategoryId;

    public Storesummary(Storesummary value) {
        this.storeId = value.storeId;
        this.name = value.name;
        this.img = value.img;
        this.lat = value.lat;
        this.lon = value.lon;
        this.hit = value.hit;
        this.reviewCount = value.reviewCount;
        this.score = value.score;
        this.regionId = value.regionId;
        this.foodCategoryId = value.foodCategoryId;
    }

    public Storesummary(
        Integer storeId,
        String  name,
        String  img,
        Double  lat,
        Double  lon,
        Integer hit,
        Integer reviewCount,
        Double  score,
        Integer regionId,
        Integer foodCategoryId
    ) {
        this.storeId = storeId;
        this.name = name;
        this.img = img;
        this.lat = lat;
        this.lon = lon;
        this.hit = hit;
        this.reviewCount = reviewCount;
        this.score = score;
        this.regionId = regionId;
        this.foodCategoryId = foodCategoryId;
    }

    public Integer getStoreId() {
        return this.storeId;
    }

    public String getName() {
        return this.name;
    }

    public String getImg() {
        return this.img;
    }

    public Double getLat() {
        return this.lat;
    }

    public Double getLon() {
        return this.lon;
    }

    public Integer getHit() {
        return this.hit;
    }

    public Integer getReviewCount() {
        return this.reviewCount;
    }

    public Double getScore() {
        return this.score;
    }

    public Integer getRegionId() {
        return this.regionId;
    }

    public Integer getFoodCategoryId() {
        return this.foodCategoryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Storesummary (");

        sb.append(storeId);
        sb.append(", ").append(name);
        sb.append(", ").append(img);
        sb.append(", ").append(lat);
        sb.append(", ").append(lon);
        sb.append(", ").append(hit);
        sb.append(", ").append(reviewCount);
        sb.append(", ").append(score);
        sb.append(", ").append(regionId);
        sb.append(", ").append(foodCategoryId);

        sb.append(")");
        return sb.toString();
    }
}
